export const TRANSLATIONS = {
  ar: {
    main_nav: "الرئيسية",
    inventory_nav: "المخزن",
    reports_settings_nav: "التقارير والإعدادات",
    inventory: "المخزن",
    dashboard: "لوحة التحكم",
    patients: "المراجعين",
    followups: "المتابعات",
    lenses: "العدسات",
    frames: "الإطارات",
    reports: "التقارير",
    settings: "الإعدادات",
    audit: "سجل التدقيق",
    superadmin: "مدير النظام",
    logout: "تسجيل الخروج",
    clinic: "العيادة",
    language: "اللغة",
    search_placeholder: "بحث عن مراجع...",
    today_patients: "مراجعين اليوم",
    today_earnings: "إيرادات اليوم",
    outstanding_debt: "الديون المعلقة",
    low_stock: "مخزون منخفض",
    monthly_revenue: "إيرادات الشهر",
    last7days: "الإيرادات — آخر 7 أيام",
    recent_patients: "آخر المراجعين",
    add_patient: "إضافة مراجع",
    edit: "تعديل",
    delete: "حذف",
    save: "حفظ",
    cancel: "إلغاء",
    name: "الاسم",
    phone: "الهاتف",
    age: "العمر",
    gender: "الجنس",
    male: "ذكر",
    female: "أنثى",
    total: "الإجمالي",
    paid: "المدفوع",
    remaining: "المتبقي",
    no_data: "لا توجد بيانات",
    all_genders: "الجنس (الكل)",
    all_debt: "الديون (الكل)",
    has_debt: "عليهم ديون",
    no_debt: "خالي من الديون",
    last_visit_time: "آخر زيارة (الكل)",
    last_7_days: "آخر 7 أيام",
    last_30_days: "آخر 30 يوماً",
    last_90_days: "آخر 90 يوماً",
    all_time: "جميع الأوقات",
    welcome_back: "أهلاً بك مجدداً",
    welcome_title: "ابدأ رحلتك مع نـور",
    signin_sub: "سجّل دخولك للمتابعة إلى لوحة التحكم",
    signup_sub: "أنشئ حساباً لعيادتك وابدأ العمل",
    login_btn: "تسجيل الدخول",
    signup_btn: "إنشاء حساب",
    no_account: "ليس لديك حساب؟",
    has_account: "لديك حساب بالفعل؟",
    register_now: "أنشئ حساباً الآن",
    signin_here: "سجّل دخولك من هنا",
    full_name_label: "الاسم الكامل",
    email_user_label: "البريد الإلكتروني / اسم المستخدم",
    password_label: "كلمة المرور",
    visit_history: "سجل الزيارات",
    total_visits: "إجمالي الزيارات",
    last_visit: "آخر زيارة",
    diagnosis_label: "التشخيص / العلاج",
    add_visit: "إضافة زيارة",
    fully_paid: "تم التسديد",
    clinical_visit: "زيارة فحص",
    patient_record: "ملف المراجع",
    current_date_label: "التاريخ الحالي",
    view_all: "عرض الكل",
    total_paid_summary: "إجمالي المدفوعات",
    total_amount_summary: "إجمالي المبالغ",
    financial_summary: "الملخص المالي",
    stock_level: "مستوى المخزون",
    reorder_point: "نقطة إعادة الطلب",
    suppliers: "الموردين",
    add_item: "إضافة مادة",
    add_supplier: "إضافة مورد",
    category: "الفئة",
    sku: "رمز المادة",
    in_stock: "في المخزن",
    out_of_stock: "نفذ من المخزن",
    unit_price: "سعر الوحدة",
    contact_person: "الشخص المسؤول",
    payment_terms: "شروط الدفع",
    prescriptions: "الوصفات الطبية",
    add_prescription: "إضافة وصفة",
    prescription_history: "سجل الوصفات",
    lens_type: "نوع العدسة",
    frame_details: "تفاصيل الإطار",
    od: "العين اليمنى (OD)",
    os: "العين اليسرى (OS)",
    sphere: "Sphere (SPH)",
    cylinder: "Cylinder (CYL)",
    axis: "Axis",
    pd: "بُعد العينين (PD)",
    prescriber: "الفاحص",
    date: "التاريخ",
    print: "طباعة",
    print_a5: "طباعة A5",
  },
  en: {
    main_nav: "Main",
    inventory_nav: "Inventory",
    reports_settings_nav: "Reports & Settings",
    inventory: "Inventory",
    dashboard: "Dashboard",
    patients: "Patients",
    followups: "Follow-ups",
    lenses: "Lenses",
    frames: "Frames",
    reports: "Reports",
    settings: "Settings",
    audit: "Audit Log",
    superadmin: "Super Admin",
    logout: "Logout",
    clinic: "Clinic",
    language: "Language",
    search_placeholder: "Search for patients...",
    today_patients: "Today's Patients",
    today_earnings: "Today's Earnings",
    outstanding_debt: "Outstanding Debt",
    low_stock: "Low Stock",
    monthly_revenue: "Monthly Revenue",
    last7days: "Revenue — Last 7 Days",
    recent_patients: "Recent Patients",
    add_patient: "Add Patient",
    edit: "Edit",
    delete: "Delete",
    save: "Save",
    cancel: "Cancel",
    name: "Name",
    phone: "Phone",
    age: "Age",
    gender: "Gender",
    male: "Male",
    female: "Female",
    total: "Total",
    paid: "Paid",
    remaining: "Remaining",
    no_data: "No data found",
    all_genders: "All Genders",
    all_debt: "Debt Status (All)",
    has_debt: "Has Debt",
    no_debt: "No Debt",
    last_visit_time: "Last Visit (All)",
    last_7_days: "Last 7 Days",
    last_30_days: "Last 30 Days",
    last_90_days: "Last 90 Days",
    all_time: "All Time",
    welcome_back: "Welcome back",
    welcome_title: "Join Noor OMS",
    signin_sub: "Please sign in to access your dashboard",
    signup_sub: "Create an account for your clinic today",
    login_btn: "Sign In",
    signup_btn: "Sign Up",
    no_account: "Don't have an account?",
    has_account: "Already have an account?",
    register_now: "Register your clinic",
    signin_here: "Sign in here",
    full_name_label: "Full Name",
    email_user_label: "Email / Username",
    password_label: "Password",
    visit_history: "Visit History",
    total_visits: "Total Visits",
    last_visit: "Last Visit",
    diagnosis_label: "Diagnosis / Treatment",
    add_visit: "Add Visit",
    fully_paid: "Fully Paid",
    clinical_visit: "Clinical Visit",
    patient_record: "Patient Record",
    current_date_label: "Current Date",
    view_all: "View All",
    total_paid_summary: "Total Paid",
    total_amount_summary: "Total Amount",
    financial_summary: "Financial Summary",
    stock_level: "Stock Level",
    reorder_point: "Reorder Point",
    suppliers: "Suppliers",
    add_item: "Add Item",
    add_supplier: "Add Supplier",
    category: "Category",
    sku: "SKU",
    in_stock: "In Stock",
    out_of_stock: "Out of Stock",
    unit_price: "Unit Price",
    contact_person: "Contact Person",
    payment_terms: "Payment Terms",
    prescriptions: "Prescriptions",
    add_prescription: "Add Prescription",
    prescription_history: "Prescription History",
    lens_type: "Lens Type",
    frame_details: "Frame Details",
    od: "Right Eye (OD)",
    os: "Left Eye (OS)",
    sphere: "Sphere (SPH)",
    cylinder: "Cylinder (CYL)",
    axis: "Axis",
    pd: "Pupillary Distance (PD)",
    prescriber: "Prescriber",
    date: "Date",
    print: "Print",
    print_a5: "Print to A5",
  },
};
